---
File.tmp: /files/tmp/
NhanVien.avatar_height: 120
NhanVien.avatar_path: /files/anhthe/
NhanVien.avatar_width: 120
Site.company_name: VNPT Đà Nẵng
Site.email: dinhthanh79@gmail.com
Site.title: Điều hành hệ thống văn bản điện tử
Site.website: http://binplus.vnptdanang.vn/
TinNhan.attach_path: /files/attachs/
VanBan.attach_path: /files/vanban/
